// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eifjjzmvhjaeuxkrxwio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpZmpqem12aGphZXV4a3J4d2lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTQwNjEsImV4cCI6MjA3MDEzMDA2MX0.DGvw4I0QzjLkZZOTbBsk8Kq-nNHZGec5uxlPBisdc7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});